version: '3.8'
services:
  db:
    image: postgres:16.0
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mozuku-db
      POSTGRES_USER: rininmmmment
      POSTGRES_PASSWORD: mypassword

  fastapi-app:
    build: ./server
    volumes:
      - "./server:/myapp"
    ports:
      - "8000:8000"
    environment: 
      - MY_ENV_VARIABLE=my_value
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
      
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./react-app:/usr/src/app
    ports:
      - "3000:3000"

volumes:
  db-data:
